name: tars

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tars image
      run: docker build ./tars/ --file ./tars/Dockerfile --tag tars:$(date +%s)
