name: framework

on: 
  push:
    branches: 
      - master
      paths:
      - .github/workflows/framework.yml
      - framework/**
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
        run: docker login -u elvisshi -p ${{ secrets.DOCKERHUB_LOGIN_PASSWO  RD }}
    - name: Build and Push framework image
      run: |
        TAG=$(date +%Y%m%d%H%M%S)
        docker build ./framework/ --file ./framework/Dockerfile --tag elvisshi/framework:${TAG}
