name: tarsnode

on: 
  push:
    branches: 
      - master
    paths:
    - .github/workflows/tarsnode.yml
    - tarsnode/**
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u elvisshi -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
    - name: Build and Push tarsnode image
      run: |
        TAG=$(date +%Y%m%d%H%M%S)
        docker build ./tarsnode/ --file ./tarsnode/Dockerfile --tag elvisshi/tarsnode:${TAG}
        docker push elvisshi/tarsnode:${TAG}
