name: tars

on: 
  push:
    branches: 
      - master
    paths:
    - .github/workflows/tars.yml
    - tars/**
      
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Docker Login
      run: docker login -u elvisshi -p ${{ secrets.DOCKERHUB_LOGIN_PASSWORD }}
    - name: Build and push tars image
      run: |
        TAG=$(date +%Y%m%d%H%M%S)
        docker build ./tars/ --file ./tars/Dockerfile --tag elvisshi/tars:${TAG}
        docker push elvisshi/tars:${TAG}
