name: tars-dev

on: 
  push:
    branches: 
      - dev

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build tars-dev image
      run: docker build ./tars/ --file ./tars/Dockerfile --tag tars:dev-$(date +%s)
